version: 2.1

orbs:
  snyk: snyk/snyk@1.1.2
  change-api: financial-times/change-api@0.25.1

references:
  filter_only_main: &filter_only_main
    branches:
      only: main
    tags:
      ignore: /.*/
  filter_ignore_main: &filter_ignore_main
    branches:
      ignore: main
    tags:
      ignore: /.*/

executors:
  python_node:
    docker:
      - image: cimg/python:3.10.2-node
  ruby:
    docker:
      - image: cimg/ruby:3.0.1

commands:
  validate_json:
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: npm install --dev
      - run:
          name: Lint JSON
          command: npm run lint
      - run:
          name: Validate Schemas with AJV
          command: npm run test

  scan_project:
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true
          severity-threshold: "high"

  readme_lint:
    steps:
      - checkout
      - run:
          name: Install and run Markdown lint tool
          command: gem install mdl && mdl README.md

jobs:
  readme:
    executor: ruby
    steps:
      - readme_lint

  validate:
    executor: python_node
    steps:
      - validate_json
      - scan_project

workflows:
  tests:
    jobs:
      - readme:
          filters:
            <<: *filter_ignore_main
      - validate:
          filters:
            <<: *filter_ignore_main

  release_to_prod:
    jobs:
      - validate:
          filters:
            <<: *filter_only_main
      - change-api/release-log:
          changeApiKey: "${CHANGE_API_KEY}"
          systemCode: "vulnerability-dashboard-api"
          environment: "prod"
          slackChannels: "cyber-security-alerts"
          requires:
            - validate
          filters:
            <<: *filter_only_main
